### PR TITLE
Another performance boost

### PR DESCRIPTION
**Pull request by tchaloupka**
Now most performance issues are with json serialization, base64 generation and GC.
As JWT header is usually still the same (mostly just the default alg + typ fields) I used the memoize helper to store the resulting header in base64 string for reuse.

This change leads to change from 4.5s to 2.5s on the simple test.

I thought of make the header CT value but it will need the API change. This way it is probably better.

### CODE REVIEW

**Comment by olehlong** [comment]
Good idea.

**Comment by olehlong** [comment]
Btw. Will it work when header_fields will have some value and will change all the time? It's not a parameter of "memoizated" function.

**Comment by olehlong** [comment]
You forgot to change header_fields to fields in inner function.

**Comment by tchaloupka** [comment]
Hmm as I look on it more, there is also a potential problem with always changing header_fields as it will lead to large hash table for memoized values. So it will probably be safer to use: https://github.com/D-Programming-Language/phobos/blob/master/std/functional.d#L993

**Comment by olehlong** [comment]
Yes, we can set maxSize to some value, 64 for example. Or any size you like more.

**Comment by olehlong** [comment]
Maybe, it would be nice to have an option to change this value or disable caching at all. What do you think about it?
Although, I don't know, if people actually use header for any additional data. Setting maxSize might be enough.

**Comment by tchaloupka** [comment]
Well it can be added as a templated function parameter. For example: string encode(int headerMemoizeSize = 64)(ref JSONValue payload, string key, JWTAlgorithm algo = JWTAlgorithm.HS256, JSONValue header_fields = null)

It can be checked for values <=0 which will disable memoization. But I'm not sure if I like it? :)

I think that it is safe to preset it for example to the suggested value of 64 and don't pollute the API with it. For cases when changes are scarce, it is enough (in most cases only one value will be used) and for many changes it will work as a small buffer for the results which can be also ok.

**Comment by olehlong** [comment]
Ok, I set maxSize to 64.

**Comment by tchaloupka** [comment]
Thx, I think that it will safely cover the most cases.

**Pull request merged**
